#!/usr/bin/env python
# coding: utf-8

import sys, tempfile, subprocess

args = sys.argv[1:]
texs = args
try:
    # move -j to be last argument if it is passed
    ii = args.index('-j')
    args = args[:ii] + args[ii+2:] + args[ii:ii+2]
    texs = args[:-2]
except ValueError:
    pass

with tempfile.NamedTemporaryFile(mode='w+') as fp:
    for ii,tex in enumerate(texs):
        win="latexmk-%d"%ii
        fp.write('(start-process "%s" "%s" "latexmk" "-pvc" "%s")\n'%(win,win,tex))
        fp.write('(split-window-right)\n')
        fp.write('(switch-to-buffer "%s")\n'%win)
        fp.write('(other-window 1)\n')
    fp.write('(start-process "monitor" "monitor" "monitor_latex_changes.sh" ')
    fp.write(' '.join(['"%s"'%arg for arg in args]))
    fp.write(')\n')
    fp.write('(switch-to-buffer "monitor")\n')
    fp.write('(balance-windows)\n')
    fp.flush()

    subprocess.run(['emacs','-nw','-l',fp.name])
