#!/bin/zsh -i
# -i ensures that "omz" function from oh-my-zsh is available

prompt_run () {
    echo ">> $@" >&2
    eval "$@"
}

if [[ "$1" == "--run-all" ]]; then
    confirm_run () {
        prompt_run "$@"
    }
else
    confirm_run () {
        prompt="Run '$@'? [Y/n] "
        typeset -l response # forces $response to be lower-case in zsh
        read "response?$prompt"
        case "$response" in
        y|yes|"")
            prompt_run "$@"
            ;;
        esac
    }
fi

prompt_run omz update
echo
prompt_run brew upgrade
echo
prompt_run brew autoremove --dry-run
echo
confirm_run brew autoremove
echo
confirm_run sudo tlmgr update --self --all
echo
confirm_run conda update -n base --all
echo
confirm_run conda update --all
