#!/bin/zsh -i
# -i ensures that "omz" function from oh-my-zsh is available

prompt_run () {
    echo ">> $@" >&2
    eval "$@"
}

confirm_run () {
    prompt="Run '$@'? [Y/n] "
    typeset -l response # forces $response to be lower-case in zsh
    read "response?$prompt"
    case "$response" in
	y|yes|"")
	    prompt_run "$@"
	    ;;
    esac
}

prompt_run omz update
echo
prompt_run brew upgrade
echo
prompt_run brew autoremove --dry-run
echo
confirm_run brew autoremove
echo
confirm_run sudo tlmgr update --self --all
echo
confirm_run mamba update --strict-channel-priority -n base --all
echo
confirm_run conda update --experimental-solver=libmamba --all
