#!/bin/zsh -i
# -i ensures that "omz" function from oh-my-zsh is available

CONFIRM=true
[[ "$1" == "--run-all" ]] && CONFIRM=false

prompt_run () {
    echo ">> $@" >&2
    eval "$@"
}

confirm_run () {
    if [[ "$CONFIRM" = "true" ]]; then
        prompt="Run '$@'? [Y/n] "
        typeset -l response # forces $response to be lower-case in zsh
        read "response?$prompt"
        case "$response" in
        y|yes|"")
            prompt_run "$@"
            ;;
        esac
    else
        prompt_run "$@"
    fi
}

prompt_run omz update
echo
prompt_run brew upgrade
echo
prompt_run brew autoremove --dry-run
echo
confirm_run brew autoremove
echo
confirm_run sudo tlmgr update --self --all
echo
confirm_run "(cd $VIRTUAL_ENV/.. && uv sync --upgrade)"
