#!/bin/zsh -i
# -i ensures that "omz" function from oh-my-zsh is available

prompt_run () {
    echo ">> $@" >&2
    eval "$@"
}

confirm_run () {
    prompt="Run '$@'? [Y/n] "
    typeset -l response # forces $response to be lower-case in zsh
    read "response?$prompt"
    case "$response" in
	y|yes|"")
	    prompt_run "$@"
	    ;;
    esac
}

prompt_run omz update
echo
prompt_run sudo port selfupdate
echo
prompt_run port outdated
echo
confirm_run sudo port upgrade outdated
echo
prompt_run port installed inactive
echo
confirm_run sudo port uninstall inactive
echo
prompt_run port echo leaves
echo
confirm_run 'while [[ "$(port echo leaves)" ]]; do sudo port uninstall leaves; done'
echo
prompt_run cd ~/macports
echo
confirm_run ./update_ports.sh
echo
prompt_run git st


cd
echo
confirm_run sudo tlmgr update --self --all
echo
confirm_run mamba update --strict-channel-priority -n base --all
echo
confirm_run mamba update --strict-channel-priority --all
