#!/usr/bin/env python
import sys
import pandas as pd

if sys.argv[1] == '--all':
    dfs = pd.read_excel(sys.argv[2],sheet_name=None)
    for k,v in dfs.items():
        print(f"{k}:")
        print("--------------")
        print(v.to_csv())
else:
    df = pd.read_excel(sys.argv[1])
    print(df.to_csv())